### ISSUE TITLE
Minibadge message collisions

### ISSUE THREAD

**Issue by kfeuz** [compukidmike/Saintcon2021#2]
I have multiple hackers challenge minibadges which each have a little eeprom to store a message to be displayed by the main badge.  I changed the i2c address for each minibadge eeprom so that they don't collide and I can see each message start to be displayed.  However, each message clobber's the previous message as soon as it the code cycles to that address.  I propose adding a variable to track if the i2c address is displaying a message and if so wait for the appropriate delay before moving on to the next message. It looks like this was the plan all along but never got fully implemented (i.e. there is an if(true) statement right before checking the next minibadge address).  I can make the code change but I don't know how to build the code and how to flash the code after that.  Can you provide some guidance on that process or point me to the right resources to do so?

**Comment by compukidmike** [comment]
Thanks for finding this bug and fixing the code!
